### ISSUE TITLE
Add high contrast option

### ISSUE THREAD

**Issue by a-hodges** [wanderers-guide/wanderers-guide-remaster#27]
The default translucent panels can be difficult to read for people with vision issues. An option to reduce transparency and make the panels opaque (usually labelled as "high contrast" in accessibility settings) would help any individuals with such issues immensely.

**Comment by Quzzar** [comment]
This is a great idea.
I believe virtually all blurred/translucent effects come from the [BlurBox](frontend/src/common/BlurBox.tsx) component (might also need to change [BlurButton](frontend/src/common/BlurButton.tsx) too). Changing that one component should adjust everything.

In terms of having an accessibility setting, should it be on a per character or per account basis? I'll leave it up to the developer. For character, let's store it under `Character.details.sheet_theme`. For account, let's hold off on adding accessibility options for now - maybe add a larger ticket for it - as I first need to finish up user security and account management.
